### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by matbech** [hanickadot/compile-time-regular-expressions#145] opened 2020-11-14 04:54 UTC
This fails to match with one of the latest updates. It was matching with v3.3.2.

```
constexpr auto Pattern1 = ctll::fixed_string{ LR"(^([\-dlsDLS][\-rwxstlRWXSTL]{9}[+]?)\s*(\d+)?\s+(\S+)?\s+(.*?)?\s+(\d+|\d+\.\d+\S)\s+([A-Za-z][a-z][a-z])\s+(\d{1,2})\s+((\d{4,4})|(\d{1,2})[:\.](\d{2,2}))\s)" };

const wchar_t begin[]{L"drwxrwxrwx   1 owner    group               0 May 26  2019 test"};
const auto end = begin + std::wcslen(begin);
const auto results = ctre::re<Pattern1>().search(begin, end);
static_assert(results.count() == 12, "unexpected count");
if (results)
{
// match
}
```

**Comment by hanickadot** [comment] 2020-11-14 08:38
Ok, next time please reopen issue instead of introducing new one, I thought it's a new error. And also report correctly last working version as this pattern is not working in v3.3.2.

It's a duplicate of #131 which I'm reopening.

**Closed by hanickadot** 2020-11-14 08:38 UTC
Labels: duplicate

**Comment by matbech** [comment] 2020-11-14 14:48
I apologize but I wasn't aware that it was the same issue. After you committed the fix for the last issue, I tested it again and it was working as expected.
