### ISSUE TITLE
Using quantifiers with `\w` won't compile for `ctre::search()`

### ISSUE THREAD

**Issue by MarioLiebisch** [hanickadot/compile-time-regular-expressions#69] opened 2019-08-08 06:47 UTC
When trying to use an expression like `\w*` or `\w+` with `ctre::search()`, the templates fail to compile properly due to reported conversion issues. This happens both with MSVC (latest 2019 release) as well as MinGW 8.1.0. This does not happen when using `ctre::match()` instead.

    ctre.hpp(3067): error C2664: 'void ctre::point_set<1>::populate(ctre::can_be_anything)': cannot convert argument 1 from 'ctre::word_chars' to 'ctre::can_be_anything'

Example code ([Compiler Explorer](https://compiler-explorer.com/z/7LKgmg)):

    #include "ctre.hpp"

    static constexpr auto pattern = ctll::fixed_string("\\w*");

    bool something(std::string_view subject) {
    #if 0
        return ctre::match<pattern>(subject);
    #else
        return ctre::search<pattern>(subject);
    #endif
    }

**Comment by hanickadot** [comment] 2019-08-08 07:30
Ok I know where the problem is, will fix it probably today.

**Comment by hanickadot** [comment] 2019-08-08 09:47
Should be fixed in latest master. Please check and in case of any problem reopen the issue.

**Closed by hanickadot** 2019-08-08 09:47 UTC

**Comment by MarioLiebisch** [comment] 2019-08-08 09:59
Yep, can confirm the issue has been fixed.
